language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"


# Installing additional tools for dionysus and boost :(
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev



install:
  - pip install .
  - pip install pytest-cov

script:
  - pytest --cov cyclenysus

after_success:
  - bash <(curl -s https://codecov.io/bash)